### ISSUE TITLE
Is this running the latest ua-parser?

### ISSUE THREAD

**Issue by nmische** [automine/TA-user-agents#1]
Looks like the ua-parser moved to https://github.com/ua-parser/uap-python and was just updated today. Could this app be updated to use that project?

**Comment by automine** [comment]
Hey nmische,

I'm sorry, I never got a notification that there was a new message waiting for me. I don't believe I am using the newest version yet, though the yaml file has been updated. I'll start planning to make the bump.

Thanks,

Dave

**Comment by automine** [comment]
Closing this in favor of the upcoming PR and version which will include a script for updating. Sorry for the delay.
