### ISSUE TITLE
Compatibility with Python 3

### ISSUE THREAD

**Issue by ehvidal** [automine/TA-user-agents#11]
Thank you very much for this app. It is very useful!

Are you planning to release a new version compatible with Python 3 soon? Can I help you somehow to do so? This would be very useful because Splunk is planning to remove Python 2.7 runtime.

Again, thank you very much for so useful app!

**Comment by automine** [comment]
A new version should be released, but I can't say that I have a timeframe for it. We are working on integrating this with our PAVO suite of apps, so part of that will be migrating it to work with Python 3 for future Splunk releases.
