### ISSUE TITLE
Could the TA be merged with the pending merge request?

### ISSUE THREAD

**Issue by thilles** [automine/TA-user-agents#4]
Hi, We heavily use the TA, but the v1.6 lacks some user agents since it was released, and it looks like the merge request https://github.com/automine/TA-user-agents/pull/3 will solve that. Can you release a v1.7.0 by merging?

**Comment by automine** [comment]
I had a discussion with the folks in SplunkCloud and, unfortunately, having a script that goes out and grabs stuff off of the web may mean that the app loses Cloud certification, which would be bad. I will circle back with the Cloud folks to see if there is anything that can be done about this. Sorry for the delay.

**Comment by lowell80** [comment]
Does it matter that the script doesn't run automatically?  And/or what if it's moved out of the "bin" folder?

**Comment by lowell80** [comment]
I've send in a new pull request #5.   The script will no longer be bundled with the app that's published on Splunk base. Instead, the README (which I assume will be copied to the Splunk Base app description) now references where to download the script for anyone who wishes to use it.

I think that should keep the Splunk Cloud team happy.  Thoughts?

**Comment by automine** [comment]
I had a discussion with some app folks at Splunk, and the new guidance is that a script being included will trigger a manual vetting, which is fine, it just means that someone will be taking a look at it, rather than the standard appcert automagic process. 

As that is the case, @lowell80 I would like to remove pr #5 and reopen and merge pr #3 , if that works for you.

Thoughts?

**Comment by lowell80** [comment]
Yes, sounds great.

**Comment by automine** [comment]
PR has been merged! Thanks @lowell80

**Comment by automine** [comment]
Ok, merged the correct one this time, and have published here and to Splunkbase as v1.7.2 Thanks again!
